// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_zeros_world();
Q_GHS_KEEP_REFERENCE(qml_register_types_zeros_world)

class zeros_worldPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    zeros_worldPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_zeros_world;
        Q_UNUSED(registration)
    }
};



#include "zeros_worldplugin_zeros_worldPlugin.moc"
